set(_CATKIN_CURRENT_PACKAGE "maze_nav")
set(maze_nav_VERSION "0.0.0")
set(maze_nav_MAINTAINER "cai <cai@todo.todo>")
set(maze_nav_PACKAGE_FORMAT "2")
set(maze_nav_BUILD_DEPENDS "geometry_msgs" "nav_msgs" "pluginlib" "roscpp" "rospy" "std_msgs" "teb_local_planner" "tf2_ros" "nav_core" "costmap_2d" "maze_mapping" "my_robot")
set(maze_nav_BUILD_EXPORT_DEPENDS "geometry_msgs" "nav_msgs" "pluginlib" "roscpp" "rospy" "std_msgs" "teb_local_planner" "tf2_ros" "nav_core" "costmap_2d" "maze_mapping" "my_robot")
set(maze_nav_BUILDTOOL_DEPENDS "catkin")
set(maze_nav_BUILDTOOL_EXPORT_DEPENDS )
set(maze_nav_EXEC_DEPENDS "geometry_msgs" "nav_msgs" "pluginlib" "roscpp" "rospy" "std_msgs" "teb_local_planner" "tf2_ros" "nav_core" "costmap_2d" "maze_mapping" "my_robot")
set(maze_nav_RUN_DEPENDS "geometry_msgs" "nav_msgs" "pluginlib" "roscpp" "rospy" "std_msgs" "teb_local_planner" "tf2_ros" "nav_core" "costmap_2d" "maze_mapping" "my_robot")
set(maze_nav_TEST_DEPENDS )
set(maze_nav_DOC_DEPENDS )
set(maze_nav_URL_WEBSITE "")
set(maze_nav_URL_BUGTRACKER "")
set(maze_nav_URL_REPOSITORY "")
set(maze_nav_DEPRECATED "")